---

- hosts: all
  become: true
  tasks:
    - name: create service directory for docker compose file
      file:
        path: /opt/vault
        state: directory
        mode: '0755'

    - name: copy vault docker compose file
      copy:
        src: ../files/docker-compose.yml
        dest: /opt/vault/docker-compose.yml
        mode: '0755'

    - name: copy vault systemd service file
      copy:
        src: ../files/vault.service
        dest: /etc/systemd/system/vault.service
        mode: '0755'

    - name: create config directory for vault json file
      file:
        path: /vault/config
        state: directory
        mode: '0755'

    - name: create config directory for vault priv
      file:
        path: /private-volume
        state: directory
        mode: '0755'

    - name: copy vault config json file
      copy:
        src: ../files/vault.json
        dest: /vault/config/vault.json

    - name: update apt repository
      command: sudo apt update
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10
    
    - name: install pip3
      command: sudo apt install -y python3-pip
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10

    - name: install docker python library
      command: pip install docker

    - name: wait for docker service
      service:
        name: docker
        state: started 

    - name: reload systemd daemons
      systemd:
        daemon_reload: true

    - name: enable vault docker-compose service
      systemd:
        name: vault
        enabled: true
        masked: no

    - name: start vault docker-compose service
      systemd:
        state: started
        name: vault
  
    # - name: launch docker container
    #   docker_container:
    #     name: vault
    #     state: started
    #     image: hashicorp/vault:1.13
    #     pull: true
    #     restart_policy: unless-stopped
    #     capabilities: IPC_LOCK
    #     published_ports: 8200:8200
    #     volumes:
    #       - /private-volume:/vault/file:rw
    #       - /vault:/vault/config:rw
    #     entrypoint: vault server -config=/vault/config/vault.json