version: "3.8"
services:
  pihole:
    image: pihole/pihole:2023.03.1
    container_name: pihole
    network: host
    volumes:
      - '/etc/pihole:/etc/pihole/'
      - '/etc-dnsmasq.d:/etc/dnsmasq.d'
    environment:
      - TZ='America/Los_Angeles'