---

- hosts: all
  become: true
  tasks:
    - name: update apt repository
      command: sudo apt update
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10
    
    - name: install pip3
      command: sudo apt install -y python3-pip
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10

    - name: install docker python library
      command: pip install docker

    - name: create pihole docker dir - /etc/pihole
      command: mkdir -p /etc/pihole

    - name: create pihole docker dir - /etc-dnsmasq.d
      command: mkdir -p /etc-dnsmasq.d
    
    - name: create service directory for docker compose file
      file:
        path: /opt/pihole
        state: directory
        mode: '0755'

    - name: copy pihole docker compose file
      copy:
        src: ../files/docker-compose.yml
        dest: /opt/pihole/docker-compose.yml
        mode: '0755'

    - name: copy pihole systemd service file
      copy:
        src: ../files/pihole.service
        dest: /etc/systemd/system/pihole.service
        mode: '0755'

    - name: wait for docker daemon service
      service:
        name: docker
        state: started 

    - name: reload systemd daemons
      systemd:
        daemon_reload: true

    - name: enable pihole docker-compose service
      systemd:
        name: pihole
        enabled: true
        masked: no

    - name: start pihole docker-compose service
      systemd:
        state: started
        name: pihole
